// <auto-generated />
using System;
using ASPSTUDENT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPSTUDENT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPSTUDENT.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("LoaiNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.NhomTinNhan", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.HasKey("MaNhom");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("NhomTinNhans");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhom", "MaNguoiDung");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThanhVienNhoms");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<string>("DuongDanTapTin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTinNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNhom");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.NhomTinNhan", b =>
                {
                    b.HasOne("ASPSTUDENT.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.SinhVien", b =>
                {
                    b.HasOne("ASPSTUDENT.Models.LopHoc", "LopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("ASPSTUDENT.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhomThamGia")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ASPSTUDENT.Models.NhomTinNhan", "NhomTinNhan")
                        .WithMany("ThanhVienNhoms")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhomTinNhan");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.TinNhan", b =>
                {
                    b.HasOne("ASPSTUDENT.Models.NhomTinNhan", "NhomTinNhan")
                        .WithMany("TinNhans")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ASPSTUDENT.Models.NguoiDung", "NguoiGui")
                        .WithMany("TinNhans")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NhomTinNhan");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.NguoiDung", b =>
                {
                    b.Navigation("NhomThamGia");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("ASPSTUDENT.Models.NhomTinNhan", b =>
                {
                    b.Navigation("ThanhVienNhoms");

                    b.Navigation("TinNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
